//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRequests
    {
        public int RequestId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string JoinMessage { get; set; }
        public string RejectReason { get; set; }
        public Nullable<bool> is_visible { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual courses courses { get; set; }
        public virtual groups groups { get; set; }
        public virtual students students { get; set; }
        public virtual teachers teachers { get; set; }
    }
}
